<a href="https://colab.research.google.com/github/IndraMadika/ML_Study/blob/main/Representasi%20Data/DataFrame_dan_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Contoh penggunaan data dengan library Pandas:

In [6]:
import pandas as pd

# Data menggunakan Pandas DataFrame
data = pd.DataFrame({'Luas Tanah': [1000, 1500, 1200, 1800, 900],
                     'Jumlah Kamar': [3, 4, 3, 4, 2],
                     'Tahun Didirikan': [1990, 1980, 2005, 1995, 2010],
                     'Harga Rumah': [500000, 700000, 600000, 800000, 450000]})

print("Pandas data :\n", data, "\n")
# Mengonversi DataFrame ke array
array_data = data.to_numpy()
print("Array data :\n",array_data)


Pandas data :
    Luas Tanah  Jumlah Kamar  Tahun Didirikan  Harga Rumah
0        1000             3             1990       500000
1        1500             4             1980       700000
2        1200             3             2005       600000
3        1800             4             1995       800000
4         900             2             2010       450000 

Array data :
 [[  1000      3   1990 500000]
 [  1500      4   1980 700000]
 [  1200      3   2005 600000]
 [  1800      4   1995 800000]
 [   900      2   2010 450000]]


Contoh penggunaan data dalam bentuk tensor (menggunakan TensorFlow)

In [7]:
import tensorflow as tf

# Data dalam bentuk tensor
data = tf.constant([[1000, 3, 1990],
                    [1500, 4, 1980],
                    [1200, 3, 2005],
                    [1800, 4, 1995],
                    [900, 2, 2010]], dtype=tf.float32)

print(data)


tf.Tensor(
[[1.000e+03 3.000e+00 1.990e+03]
 [1.500e+03 4.000e+00 1.980e+03]
 [1.200e+03 3.000e+00 2.005e+03]
 [1.800e+03 4.000e+00 1.995e+03]
 [9.000e+02 2.000e+00 2.010e+03]], shape=(5, 3), dtype=float32)


Dalam contoh pertama, data diwakili oleh objek Pandas DataFrame yang memiliki kolom-kolom yang berbeda sebagai fitur dan target. Data tersebut kemudian dikonversi menjadi array menggunakan metode to_numpy() untuk digunakan dalam model machine learning.

Dalam contoh kedua, data direpresentasikan dalam bentuk tensor menggunakan TensorFlow. Tensor adalah struktur data yang digunakan di TensorFlow untuk menyimpan dan memanipulasi data dalam bentuk array multidimensi.

**FYI**
Pandas dan NumPy adalah dua library populer dalam bahasa pemrograman Python yang digunakan untuk analisis dan manipulasi data.

Dalam ringkasan, Pandas digunakan untuk analisis data tabular dan manipulasi data terstruktur, sedangkan NumPy digunakan untuk komputasi numerik, pemrosesan data numerik, dan operasi matriks. Keduanya sangat berguna dalam pemodelan data dan analisis numerik dalam Python.




Berikut ini adalah beberapa cara umum untuk membuat tensor data:

Menggunakan TensorFlow:

Menggunakan fungsi tf.constant() untuk membuat tensor konstan.
Menggunakan fungsi tf.Variable() untuk membuat tensor variabel.
Menggunakan operasi dan fungsi TensorFlow lainnya seperti tf.zeros(), tf.ones(), tf.random.normal(), atau tf.random.uniform().

Menggunakan NumPy:

Menggunakan fungsi np.array() untuk membuat tensor dari array NumPy.
Menggunakan fungsi NumPy lainnya seperti np.zeros(), np.ones(), np.random.normal(), atau np.random.uniform() untuk membuat tensor dengan nilai nol, satu, atau acak.

In [9]:
# Contoh penggunaan TensorFlow:

import tensorflow as tf

# Membuat tensor konstan
tensor_const = tf.constant([1, 2, 3, 4, 5])

# Membuat tensor variabel
tensor_var = tf.Variable([6, 7, 8, 9, 10])

# Membuat tensor dengan nilai nol
tensor_zeros = tf.zeros(shape=(3, 3))

# Membuat tensor dengan nilai acak
tensor_random = tf.random.uniform(shape=(2, 2))

# Menampilkan hasil
print("Tensor Konstan:")
print(tensor_const)

print("Tensor Variabel:")
print(tensor_var)

print("Tensor dengan Nilai Nol:")
print(tensor_zeros)

print("Tensor dengan Nilai Acak:")
print(tensor_random)


Tensor Konstan:
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
Tensor Variabel:
<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 6,  7,  8,  9, 10], dtype=int32)>
Tensor dengan Nilai Nol:
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
Tensor dengan Nilai Acak:
tf.Tensor(
[[0.5351337  0.1273483 ]
 [0.4225917  0.14349282]], shape=(2, 2), dtype=float32)


In [10]:
#Contoh penggunaan NumPy:
import numpy as np

# Membuat tensor dari array NumPy
tensor_from_numpy = np.array([1, 2, 3, 4, 5])

# Membuat tensor dengan nilai nol
tensor_zeros = np.zeros((3, 3))

# Membuat tensor dengan nilai acak
tensor_random = np.random.uniform(size=(2, 2))

# Menampilkan hasil
print("Tensor dari Array NumPy:")
print(tensor_from_numpy)

print("Tensor dengan Nilai Nol:")
print(tensor_zeros)

print("Tensor dengan Nilai Acak:")
print(tensor_random)


Tensor dari Array NumPy:
[1 2 3 4 5]
Tensor dengan Nilai Nol:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Tensor dengan Nilai Acak:
[[0.33962015 0.06785462]
 [0.52867527 0.13828098]]
