<a href="https://colab.research.google.com/github/IndraMadika/ML_Study/blob/main/Representasi%20Data/Multiclass_classification_dengan_berbagai_metode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Contoh kodingan untuk multiclass classification dengan berbagai metode encoding, yaitu One-Hot Encoding, Integer Encoding, Binary Encoding, dan Label Encoding.

**Jenis Tugas Klasifikasi: Binary Classification**

1. Jumlah Kategori: 2 (Misalnya, kategori "Positif" dan "Negatif") <br>
    <ul>
      <li>One-Hot Encoding: [1, 0] untuk kategori "Positif" dan [0, 1] untuk kategori "Negatif"
      <li>Integer Encoding: 0 untuk kategori "Positif" dan 1 untuk kategori "Negatif"
      <li>Binary Encoding: 0 untuk kategori "Positif" dan 1 untuk kategori "Negatif"
      <li>Label Encoding: 0 untuk kategori "Positif" dan 1 untuk kategori "Negatif"
    </ul>
**Jenis Tugas Klasifikasi: Multiclass Classification**

2. Jumlah Kategori: 3 (Misalnya, kategori "A", "B", dan "C")
    <ul>
      <li>One-Hot Encoding: [1, 0, 0] untuk kategori "A", [0, 1, 0] untuk kategori "B", dan [0, 0, 1] untuk kategori "C"
      <li>Integer Encoding: 0 untuk kategori "A", 1 untuk kategori "B", dan 2 untuk kategori "C"
      <li>Binary Encoding: 00 untuk kategori "A", 01 untuk kategori "B", dan 10 untuk kategori "C"
      <li>Label Encoding: 0 untuk kategori "A", 1 untuk kategori "B", dan 2 untuk kategori "C"
    </ul>
**Jenis Tugas Klasifikasi: Multilabel Classification**

3. Jumlah Kategori: 4 (Misalnya, kategori "A", "B", "C", dan "D")
  <ul>
    <li>One-Hot Encoding: [1, 0, 0, 1] untuk kategori "A" dan "D", [0, 1, 1, 0] untuk kategori "B" dan "C"
    <li>Integer Encoding: 0 untuk kategori "A", 1 untuk kategori "B", 2 untuk kategori "C", dan 3 untuk kategori "D"
    <li>Binary Encoding: 0101 untuk kategori "A" dan "D", 1010 untuk kategori "B" dan "C"
    <li>Label Encoding: Tidak relevan untuk tugas multilabel classification
  </ul>

In [11]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, LabelBinarizer, OrdinalEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Contoh data multiclass
data = pd.DataFrame({
    'feature_1': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    'label': ['Class 1', 'Class 2', 'Class 3', 'Class 1', 'Class 2', 'Class 3', 'Class 1', 'Class 2', 'Class 3', 'Class 1']
})

# One-Hot Encoding
one_hot_encoder = OneHotEncoder(sparse=False)
one_hot_encoded = one_hot_encoder.fit_transform(data[['feature_1']])
print("One-Hot Encoded:")
print(one_hot_encoded)

# Integer Encoding
integer_encoder = LabelEncoder()
integer_encoded = integer_encoder.fit_transform(data['label'])
print("\nInteger Encoded:")
print(integer_encoded)

# Binary Encoding
binary_encoder = LabelBinarizer()
binary_encoded = binary_encoder.fit_transform(data['label'])
print("\nBinary Encoded:")
print(binary_encoded)

# Label Encoding
label_encoder = OrdinalEncoder()
label_encoded = label_encoder.fit_transform(data[['feature_1']])
print("\nLabel Encoded:")
print(label_encoded)

One-Hot Encoded:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

Integer Encoded:
[0 1 2 0 1 2 0 1 2 0]

Binary Encoded:
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]]

Label Encoded:
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]
 [7.]
 [8.]
 [9.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
